demo/demo/urls.py
from django.conf.urls import url
from . import apis
from .views import DemoView
urlpatterns = [
    url(r'^$', DemoView.as_view(), name="demo"),
    url(r'^svm/(?P<C>\d+\.\d+)/$', apis.svm),
    url(r'^clf/(?P<sentence>[\w|\W]+)/$', apis.clf),
    url(r'^wat/(?P<sentence>[\w|\W]+)/$', apis.wat),
]

demo/wat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from .views import (
    IndexView,
    SuccessView,
    FailedView,
    WatView,
)
from correction.views import (
    CorrectView,
    ValidateView,
)
 
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^home/',RedirectView.as_view(url='/')),
    url(r'^success/', SuccessView.as_view(), name='success'),
    url(r'^failed/', FailedView.as_view(), name='failed'),
    url(r'^correct/', CorrectView.as_view(), name="correct"),
    url(r'^validate/', ValidateView.as_view(), name="validate"),
    url(r'^wat/', WatView.as_view(), name='wat'),
    url(r'^demo/', include('demo.urls')),
]

demo/correction/models.py
from django.db import models
from django.utils import timezone
import random as rd
# Create your models here.



class DNCQuerySet(models.QuerySet):
    def defaults(self):
        return self.filter(status='default')

    def corrections(self):
        return self.filter(status='corrected')

    def validations(self):
        return self.filter(status='validated')

    def random_defaults(self, size):
        rd.seed(rd.randint(1, 10000))
        qs = self.filter(status='default') 
        return [qs.filter(data_id=rd.randint(1, len(qs)))[0] for _ in range(size)]

class DataNeedsCorrection(models.Model):
    data_id = models.AutoField(primary_key=True)
    category = models.ForeignKey('WatCategory', on_delete=models.CASCADE)
    originalText = models.CharField(max_length=300)
    translatedText = models.CharField(max_length=300)
    status = models.CharField(max_length=20, choices=(("default", "Default"),("corrected","Corrected"),("validated", "Validated")))
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()
    objects = DNCQuerySet.as_manager()

    class Meta:
        verbose_name_plural = "Data needs to be corrected"

    def __unicode__(self):
        return self.originalText

    def __str__(self):
        return self.originalText

    def save(self, *args, **kwargs):
        if not self.data_id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(DataNeedsCorrection, self).save(*args, **kwargs)




class DataCorrected(models.Model):
    data_id = models.AutoField(primary_key=True)
    referenceData = models.ForeignKey('DataNeedsCorrection', on_delete=models.CASCADE)
    correctedText = models.CharField(max_length=300)
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()
    class Meta:
        verbose_name_plural = 'Data Corrected'

    def __unicode__(self):
        return self.correctedText

    def __str__(self):
        return self.correctedText

    def save(self, *args, **kwargs):
        if not self.data_id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(DataCorrected, self).save(*args, **kwargs)

class DataValidated(models.Model):
    data_id = models.AutoField(primary_key=True)
    referenceData = models.ForeignKey('DataNeedsCorrection', on_delete=models.CASCADE)
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()

    class Meta:
        verbose_name_plural = "Validated Data"

    def save(self, *args, **kwargs):
        if not self.data_id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(DataValidated,self).save(*args, **kwargs)

class WatCategory(models.Model):
    category_id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    example = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = "Word Analogy Reasoning Task Categories"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

demo/demo/models.py
from django.db import models

# Create your models here.

demo/mainmenu/models.py
from django.db import models

# Create your models here.
class Mainmenu(models.Model):
    name = models.CharField(max_length=30,)
    description = models.TextField()
    slug = models.SlugField(max_length=50, db_index=True)
    path = models.CharField(max_length=30,)
    order = models.PositiveIntegerField()
    isVisible = models.BooleanField(default=False)

    class Meta:
        ordering = ["order"]


    def __unicode__(self):
        return self.name
    
    def __str__(self):
        return self.name

demo/correction/forms.py
from django import forms
from .models import (
    DataNeedsCorrection, 
    DataCorrected,
    DataValidated,
    WatCategory
)

class DataCorrectForm(forms.ModelForm):
    class Meta:
        model = DataCorrected
        fields = [
            'referenceData',
            'correctedText'
        ]


class DataValidateForm(forms.ModelForm):
    class Meta:
        model = DataValidated
        fields = [
            'referenceData',
        ]

demo/correction/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from mainmenu.models import Mainmenu
from wat.views import IndexView


from .models import (
    DataNeedsCorrection,
    DataCorrected,
    DataValidated
)
from .forms import (
    DataCorrectForm, 
    DataValidateForm,
)

class CorrectView(IndexView):
    template = "correct.html"
    SIZE = 10
    form_class = DataCorrectForm
    context = dict(IndexView.context)
    context.update({
        "title": 'Data Correction',
        "form": form_class(),
        "ncs": DataNeedsCorrection.objects.random_defaults(SIZE)
    })
    def get_form(self, request):
        return self.form_class(request)

    def post(self, request, *args, **kwargs):
        form = self.get_form(request.POST or None)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self, form):
        return HttpResponseRedirect('/success')
    
    def form_invalid(self, form):
        return HttpResponseRedirect('/failed')


class ValidateView(IndexView):
    template = "validate.html"
    form_class = DataValidateForm
    context = dict(IndexView.context)
    context.update({
        "title":'Data Validation',
        "form":form_class,
        "cds": DataCorrected
    })
    def get_form(self, request):
        return self.form_class(request)

    def post(self, request, *args, **kwargs):
        form = self.get_form(request.POST or None)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    

demo/demo/views.py
from django.shortcuts import render
from wat.views import IndexView


class DemoView(IndexView):
    template = "demo.html"
    context = dict(IndexView.context)

demo/mainmenu/views.py
from django.shortcuts import render

# Create your views here.

demo/wat/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from mainmenu.models import Mainmenu


class IndexView(View):
    template = "index.html"
    context = {
        "menus": list(filter(lambda x:x.isVisible, Mainmenu.objects.all())),
        "title": "Korean Sentiment Analysis"
    }
    def get(self, req, *args, **kwargs):
        return render(req, self.template, self.context)


class SuccessView(IndexView):
    template = "success.html"

class FailedView(IndexView):
    template = "failed.html"

class WatView(IndexView):
    template = 'wat.html'
    

demo/correction/templates/correct.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <h2>Correction</h2>
    <div class="row">
        <div id="needs-correction" class="col s10">
            <ul class="column-header">
                <li class="col s2"><strong>Category</strong></li>
                <li class="col s5"><strong>Original Text</strong></li>
                <li class="col s5"><strong>Translated Text</strong></li>
            </ul>
            <ul>
                {% for nc in ncs %}
                <li class="row nc-data-row" data-nc-did="{{nc.data_id}}" data-nc-category="{{nc.category}}" data-nc-original-text="{{nc.originalText}}" data-nc-translated-text="{{nc.translatedText}}">
                    <ul>
                        <li class="col s2">{{nc.category}}</li>
                        <li class="col s5">{{nc.originalText}}</li>
                        <li class="col s5">{{nc.translatedText}}</li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col s8">
            <form id="correction-suggest" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn" type="submit">제출!</button>
            </form>
        </div>
    </div>
</div>




{% endblock content %}
{% block pagescript %}
<script>
(function(doc, win, $, undefined){
    'use strict';
    $('.nc-data-row').click(function(e){
        var $this = $(this);
        var ttext = $this.attr("data-nc-translated-text");
        var did = $this.attr('data-nc-did');
        var select_id_string = $('#id_referenceData').attr('data-select-id');
        console.log(did);
        doc.getElementById('id_correctedText').value = ttext;
        doc.getElementById('id_referenceData').value = +did;
        //console.log(select_id_string);
        //$('#select-options-'+ select_id_string).children()[+doc.getElementById('id_referenceData').value].click();
    });

})(document, window, $);
</script>
{% endblock pagescript %}

demo/correction/templates/failed.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h5>Failed!</h5>
    </div>
</div>
{% endblock content %}

demo/correction/templates/success.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h5>Success!</h5>
    </div>
</div>
{% endblock content %}

demo/correction/templates/validate.html
{% extends "index.html" %}

{% block content %}
<div class="container col s8">
    <h2>Validation</h2>
    <div class="row">
        <div class="col s8">
            <form>
                {{form.as_p}}
                <button class="btn" type="submit" method="POST">제출!</button>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

demo/demo/templates/demo.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12">
            <h3>Demo page</h3>
        </div>
    </div>
    <div class="row">
        <form id="demo">
            <div class="col s12">    
                <label for="sentence-input">문장을 입력해주세요!</label>
                <input name="sentence-input" value="" placeholder="최고의 영화였습니다."></textarea>
                <button class="btn">제출</button>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col s12 l8">
            <div class="row">
                <label class="col">결과</label>
            </div>
            <div class="row">
                <div id="result" class="col s12">
                    <!-- AJAX contents goes here -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block pagescript %}
<script>
(function(win, doc, $, undefined){
    'use strict';
    $('#demo button').on('click', function(e){
        var resultDOM = document.getElementById('result');
        resultDOM.innerHTML = '';
        e.preventDefault();
        var sentence_input = document.getElementById('sentence-input').value;
        var result = document.getElementById('result');
        $.ajax({
            type: 'GET',
            url: win.location.origin + '/demo/wat/' + sentence_input,
        })
        .done(function(data) {
                var d = data[0];
                var resultcode = d.resultcode;
                if (resultcode) {
                    var toRender = doc.createElement('div');
                    var wordsWrapper = doc.createElement('ul');
                    var listHeader = doc.createElement('li');
                    var answerDOM = doc.createElement('h3');
                    var iconDOM = doc.createElement('i');
                    iconDOM.className = 'material-icons small';
                    iconDOM.innerHTML = 'done';
                    answerDOM.innerHTML = d.answer;
                    answerDOM.appendChild(iconDOM);
                    listHeader.className = "collection-header";
                    listHeader.appendChild(answerDOM);
                    wordsWrapper.className = 'collection with-header';
                    wordsWrapper.appendChild(listHeader);
                    for(var i = 0 ; i < d.words.length; i++){
                        var [word, prob] = d.words[i];
                        var listElem = doc.createElement('li');
                        var nameDOM = doc.createElement('span');
                        var probDOM = doc.createElement('span');
                        listElem.className = 'collection-item';
                        nameDOM.className = 'chip';
                        nameDOM.innerHTML = word;
                        probDOM.innerHTML = prob;
                        listElem.appendChild(nameDOM);
                        listElem.appendChild(probDOM);
                        wordsWrapper.appendChild(listElem);
                    }
                    toRender.appendChild(wordsWrapper);
                } else {
                    var toRender = doc.createElement('span');
                    toRender.innerHTML = d.answer;
                }
                resultDOM.appendChild(toRender);
            })
        .fail(function() {
                console.log('unknown fail!');
            })
        .always(function() {
                console.log('GET - ' + sentence_input);
            });
    });

    $('.help-button').click(function(){
        $('.modal-popup').show();
    });
    $('.close').click(function(){
        $('.modal-popup').hide();
    })
})(window, document, jQuery);
</script>
{% endblock pagescript %}

demo/wat/templates/correct.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <h2>Correction</h2>
    <div class="row">
        <div id="needs-correction" class="col s10">
            <ul class="column-header">
                <li class="col s2"><strong>Category</strong></li>
                <li class="col s5"><strong>Original Text</strong></li>
                <li class="col s5"><strong>Translated Text</strong></li>
            </ul>
            <ul>
                {% for nc in ncs %}
                <li class="row nc-data-row" data-nc-did="{{nc.data_id}}" data-nc-category="{{nc.category}}" data-nc-original-text="{{nc.originalText}}" data-nc-translated-text="{{nc.translatedText}}">
                    <ul>
                        <li class="col s2">{{nc.category}}</li>
                        <li class="col s5">{{nc.originalText}}</li>
                        <li class="col s5">{{nc.translatedText}}</li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col s8">
            <form id="correction-suggest" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn" type="submit">제출!</button>
            </form>
        </div>
    </div>
</div>




{% endblock content %}
{% block pagescript %}
<script>
(function(doc, win, $, undefined){
    'use strict';
    $('.nc-data-row').click(function(e){
        var $this = $(this);
        var ttext = $this.attr("data-nc-translated-text");
        var did = $this.attr('data-nc-did');
        var select_id_string = $('#id_referenceData').attr('data-select-id');
        console.log(did);
        doc.getElementById('id_correctedText').value = ttext;
        doc.getElementById('id_referenceData').value = +did;
        //console.log(select_id_string);
        //$('#select-options-'+ select_id_string).children()[+doc.getElementById('id_referenceData').value].click();
    });

})(document, window, $);
</script>
{% endblock pagescript %}

demo/wat/templates/failed.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h5>Failed!</h5>
    </div>
</div>
{% endblock content %}

demo/wat/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{{ title }}</title>
        <link rel="icon" href="{% static "wat/favicon.ico" %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static "wat/css/reset.css" %}" />
        <link rel="stylesheet" href="{% static "wat/css/styles.css" %}" />
    </head>
    <body>
        <header>
            <nav id="nav-mobile" class="navigation">
                <ul class="container"> 
                    {% for menu in menus %}
                    <li><a href="/{{menu.path}}">{{ menu.name }}</a></li> 
                    {% endfor %}
                </ul>
            </nav>
        </header>   
        <main>
            {% block content %}
            <div class="container">
                <ul>
                    <section>
                        <h2>
                            <strong><img style="width:100%;" src="{% static "wat/images/logo.jpg" %}"></img></strong>
                        </h2>
                    </section>
                    <section>
                        <p>이 데모 웹사이트는 Attention Network을 이용한 한국어 감정 분석에 대한 내용을 담고 있습니다.</p>
                    </section>
                    <section>
                        <div class="introduction-wrapper">
                        <ul class="level0">
                            <li>
                                <h5 class="sub-title">1. 데이터 소스</h5>
                                <ul class="collection level1">
                                    <li class="collection-item">
                                        <span class="content-key">Wikipedia DUMP</span>
                                        <span class="content-value">총 4481만여개의 단어를 이용한 학습</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">네이버 영화평</span>
                                        <span class="content-value">총 160여만개의 단어를 이용한 테스트</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">Word Analogy Reasoning sets</span>
                                        <span class="content-value"><a href="http://download.tensorflow.org/data/questions-words.txt">Question words</a>을 번역 + 데이터 추가</span>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <h5 class="sub-title">2. 데이터 전처리</h5>
                                <ul class="collection level1">
                                    <li class="collection-item">
                                        <span class="content-key">Data Parsing</span>
                                        <span class="content-value">필요 없는 태그 제거 및 컨텐츠 파싱</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">Pos Tagging</span>
                                        <span class="content-value">Konlpy Twitter를 이용한 품사 태깅</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">Lemmatization</span>
                                        <span class="content-value">태깅 데이터에 기반</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">Word Embedding</span>
                                        <span class="content-value">Word2Vec model을 이용한 word representation vector생성</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">Padding</span>
                                        <span class="content-value">embedded vector를 모델에 맞는 데이터의 Shape을 맞춰주는 과정</span>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <h5 class="sub-title">3. 모델 수립</h5>
                                <ul class="collection level1">
                                    <li class="collection-item">
                                        <span class="content-key">SVM</span>
                                        <span class="content-value">Support Vector Machine을 이용한 baseline experiment</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">CNN</span>
                                        <span class="content-value">CNN을 이용한 baseline experiment</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">RNN</span>
                                        <span class="content-value">RNN을 이용한 baseline experiment</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">Attention Network Convolutional layer added</span>
                                        <span class="content-value">Attention이 적용된 RNN</span>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <h5 class="sub-title">4. 모델 검증</h5>
                                <ul class="collection level1">
                                    <li class="collection-item">
                                        <span class="content-key">Word2Vec</span>
                                        <span class="content-value">Word Analogy Reasoning Set을 이용한 검증</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">CNN</span>
                                        <span class="content-value">Testset - Naver 영화평</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">RNN</span>
                                        <span class="content-value">Testset - Naver 영화평</span>
                                    </li>
                                    <li class="collection-item">
                                        <span class="content-key">Attention Network Convolutional layer added</span>
                                        <span class="content-value">Testset - Naver 영화평</span>
                                    </li>
                                </ul> 
                            </li>    
                        </ul>
                        </div>
                    </section>
                </ul>
            </div>
            {% endblock content %}
        </main>
        {% comment %} <footer class="page-footer">
            
        </footer> {% endcomment %}
    </body>
    {% block TopLevelHTMLBlocks %}
    {% endblock TopLevelHTMLBlocks %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js"></script>
    {% block pagescript %}

    {% endblock pagescript %}
    <script>
        $(document).ready(function() {
            $('select').material_select();
        });
    </script>
</html>

demo/wat/templates/success.html
{% extends "index.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h5>Success!</h5>
    </div>
</div>
{% endblock content %}

demo/wat/templates/validate.html
{% extends "index.html" %}

{% block content %}
<div class="container col s8">
    <h2>Validation</h2>
    <div class="row">
        <div class="col s8">
            <form>
                {{form.as_p}}
                <button class="btn" type="submit" method="POST">제출!</button>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

demo/wat/templates/wat.html
{% extends "index.html" %}
{% load static from staticfiles %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12">
            <h3>Word Analogy Reasoning <i class="help-button material-icons">help</i></h3>
        </div>
    </div>
    <div class="row">
        <form id="wat" class="col s12 l8">
            {% csrf_token %}
            <div class="s12 l8">    
                <label for="sentence-input">테스트 할 문장을 단어들을 입력해주세요!</label>
                <input id="sentence-input"  name="sentence-input" value="" placeholder="한국 서울 도쿄"></textarea>
            </div>
            <div class="s12 l4" style="line-height:80px;">
                <button class="btn" type="submit">제출</button>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col s12 l8">
            <div class="row">
                <label class="col">결과</label>
            </div>
            <div class="row">
                <div id="result" class="col s12">
                    <!-- AJAX contents goes here -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block TopLevelHTMLBlocks %}
<div class="modal-popup">
    <div class="card">
        <div class="close-wrapper"><i class="close material-icons">close</i></div>
        <div class="card-image">
            <img src="{% static "wat/images/wat.PNG" %}">
        </div>
        <div class="card-content">
            <div class="card-title">Word Analogy Reasoning Tasks</div>
            <p>Word Analogy Reasoning Tasks는 Word Embedding의 결과를 검증하기 위해 사용되는 일련의 단어열 집합입니다. 
               이는 Word Embedding의 결과물이 다차원 공간상의 벡터이기에 이 벡터들 간에 어떤 관계가 있을 것이다라는 전제를 함의하고 있습니다.
               예를 들어, 한국의 수도는 서울, 일본의 수도는 도쿄입니다. 그렇다면, `한국`과 `서울`의 관계는 아마도 `일본`과 `도쿄`의
               관계가 성립할 것이라는 가정입니다. 
            </p>
            <div class="reference-wrapper">
                <div class="sub-title">Reference</div>
                <div>
                    <a href="http://www.aclweb.org/anthology/N13-1090">Linguistic Regularities in Continuous Space Word Representations - Mikolov el al. (2013)</a>
                </div> 
                <div>
                    <a href="http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality">Distributed Representations of Words and Phrases and their Compositionality - Mikolov et al. (2013) </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock TopLevelHTMLBlocks %}
{% block pagescript %}
<script>
(function(win, doc, $, undefined){
    'use strict';
    $('#wat button').on('click', function(e){
        var resultDOM = document.getElementById('result');
        resultDOM.innerHTML = '';
        e.preventDefault();
        var sentence_input = document.getElementById('sentence-input').value;
        var result = document.getElementById('result');
        $.ajax({
            type: 'GET',
            url: win.location.origin + '/demo/wat/' + sentence_input,
        })
        .done(function(data) {
                var d = data[0];
                var resultcode = d.resultcode;
                if (resultcode) {
                    var toRender = doc.createElement('div');
                    var wordsWrapper = doc.createElement('ul');
                    var listHeader = doc.createElement('li');
                    var answerDOM = doc.createElement('h3');
                    var iconDOM = doc.createElement('i');
                    iconDOM.className = 'material-icons small';
                    iconDOM.innerHTML = 'done';
                    answerDOM.innerHTML = d.answer;
                    answerDOM.appendChild(iconDOM);
                    listHeader.className = "collection-header";
                    listHeader.appendChild(answerDOM);
                    wordsWrapper.className = 'collection with-header';
                    wordsWrapper.appendChild(listHeader);
                    for(var i = 0 ; i < d.words.length; i++){
                        var [word, prob] = d.words[i];
                        var listElem = doc.createElement('li');
                        var nameDOM = doc.createElement('span');
                        var probDOM = doc.createElement('span');
                        listElem.className = 'collection-item';
                        nameDOM.className = 'chip';
                        nameDOM.innerHTML = word;
                        probDOM.innerHTML = prob;
                        listElem.appendChild(nameDOM);
                        listElem.appendChild(probDOM);
                        wordsWrapper.appendChild(listElem);
                    }
                    toRender.appendChild(wordsWrapper);
                } else {
                    var toRender = doc.createElement('span');
                    toRender.innerHTML = d.answer;
                }
                resultDOM.appendChild(toRender);
            })
        .fail(function() {
                console.log('unknown fail!');
            })
        .always(function() {
                console.log('GET - ' + sentence_input);
            });
    });

    $('.help-button').click(function(){
        $('.modal-popup').show();
    });
    $('.close').click(function(){
        $('.modal-popup').hide();
    })
})(window, document, jQuery);
</script>
{% endblock pagescript %}
